twitter:
    consumer_key: yourkeyhere
    consumer_secret: yoursecrethere
    access_token: youraccesstokenhere
    access_secret: youraccesssecrethere

twilio:
    accountSID: youraccountsidhere
    authToken: yourauthtokenhere
    myTwilioNumber: yourtwilionumberhere
    myCellNumber: yourrecevingnumberhere